version: '2'
services:
  proxy:
    image: traefik
    command: --web --api --docker --logLevel=DEBUG
    restart: always
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  webgateway:
    driver: bridge
