version: "2"
services:

  mariadb:
    networks:
      - web
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    networks:
      - web
    environment:
      ## Read instructions at https://wodby.com/stacks/wordpress/docs/local/xdebug/
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_XDEBUG_PORT: 9001
      PHP_XDEBUG_REMOTE_PORT: 9001

  mailhog:
    networks:
      - web

  apache:
    networks:
      - web

  portainer:
    networks:
      - web

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    networks:
      - web
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

networks:
  web:
    external:
      name: traefik_webgateway
